spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true

logging:
  level:
    ROOT: ERROR
