spring:
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true

parse:
  delimiter: \t
  fileNameQuestion: questions
  fileNameExt: .csv
exam:
  separatorLine: ------------------------------
  nameExam: TestJava
  delimiterAnswers: ','
  numberQuestion: '№_'
  local: ru-RU
