spring:
  messages:
    basename: i18n/messages

parse:
  delimiter: \t
  fileNameQuestion: questions.csv
exam:
  separatorLine: ------------------------------
  nameExam: TestJava
  delimiterAnswers: ','
  numberQuestion: '№_'
