spring:
  messages:
    encoding: UTF-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:h2:mem:librarydb
  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: false
