spring:
#  mongodb:
#    embedded:
#      version: 3.5.5
  data:
    mongodb:
      database: librarydb
#      port: 0
      port: 27017
      host: localhost
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.homework.librarymongo.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

#logging:
#  level:
#    ROOT: ERROR
