spring:
  data:
    mongodb:
      database: librarydb
      port: 27017
      host: localhost
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.homework.librarymongo.mongock.changelog

#logging:
#  level:
#    ROOT: ERROR
